version: '3.8'

services:
    mysql:
        image: mysql:8
        container_name: oclarity-mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: oclaritybiz_bd
            MYSQL_USER: theber
            MYSQL_PASSWORD: theber_password
        ports:
            - "3306:3306"
        volumes:
            - ./data:/var/lib/mysql
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Opcional

    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: oclarity-app
        depends_on:
            - mysql
        ports:
            - "8081:8080"
        environment:
            DB_URL: jdbc:mysql://mysql:3306/oclaritybiz_bd
            DB_USER: theber
            DB_PASS: theber_password